server:
  port: 2222
spring: 
  datasource: 
    url: jdbc:postgresql://192.168.99.100:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    show-sql: true
